<Project>
  <PropertyGroup>
    <Version>2.1.0</Version>
    <AssemblyVersion>2.1.0.0</AssemblyVersion>
    <FileVersion>2.1.0.0</FileVersion>
    <InformationalVersion>2.1.0 (Full Engine Upgrade)</InformationalVersion>
    <Company>OpenMedia</Company>
    <Product>OpenMedia Ecosystem</Product>
    <Copyright>Copyright © 2026 OpenMedia Project</Copyright>
  </PropertyGroup>
</Project>
