<Project>
  <PropertyGroup>
    <Version>2.0.0</Version>
    <AssemblyVersion>2.0.0.0</AssemblyVersion>
    <FileVersion>2.0.0.0</FileVersion>
    <InformationalVersion>2.0.0 (Release v2.0)</InformationalVersion>
    <Company>OpenMedia</Company>
    <Product>OpenMedia Ecosystem</Product>
    <Copyright>Copyright © 2026 OpenMedia Project</Copyright>
  </PropertyGroup>
</Project>
