#include <gtest/gtest.h>
#include <openmedia/io/FileSource.h>
#include <openmedia/io/SnapshotOutput.h>
#include <openmedia/codecs/CodecFactory.h>
#include <filesystem>

using namespace openmedia::core;
using namespace openmedia::io;
using namespace openmedia::codecs;

TEST(SnapshotIntegrationTest, ExtractThumbnail) {
    std::string inputFilePath = "test_transcode_input.h264"; // Reusing the file generated by transcode test
    std::string snapshotFilePath = "snapshot_output.png";

    if (std::filesystem::exists(snapshotFilePath)) std::filesystem::remove(snapshotFilePath);

    // Only run if input file exists (generated by another test or pre-existing)
    if (!std::filesystem::exists(inputFilePath)) {
        GTEST_SKIP() << "Input file " << inputFilePath << " not found, skipping snapshot test.";
    }

    auto fileSource = std::make_shared<FileSource>();
    ASSERT_TRUE(fileSource->Open(inputFilePath).has_value());

    auto decoder = CodecFactory::CreateDecoder(VideoCodec::H264);
    ASSERT_TRUE(decoder != nullptr);
    ASSERT_TRUE(decoder->Initialize().has_value());

    auto snapshotOut = std::make_shared<SnapshotOutput>();
    ASSERT_TRUE(snapshotOut->Initialize().has_value());
    ASSERT_TRUE(snapshotOut->SaveNextFrame(snapshotFilePath).has_value());

    ASSERT_TRUE(fileSource->Start().has_value());
    ASSERT_TRUE(decoder->Start().has_value());

    bool snapshotTaken = false;

    // Pull frame from source -> decode -> pass first raw frame to snapshot output
    while (!snapshotTaken) {
        auto pullRes = fileSource->PullFrame();
        if (!pullRes || !pullRes.value()) break;

        auto pushDec = decoder->PushFrame(pullRes.value());
        ASSERT_TRUE(pushDec.has_value());

        while (true) {
            auto rawRes = decoder->PullFrame();
            if (!rawRes || !rawRes.value()) break;

            // We got a raw frame! Send to snapshot output
            auto pushSnap = snapshotOut->PushFrame(rawRes.value());
            ASSERT_TRUE(pushSnap.has_value());
            snapshotTaken = true;
            break; // only need one frame
        }
    }

    (void)fileSource->Stop();
    (void)decoder->Stop();
    fileSource->Close();
    (void)snapshotOut->Stop();

    ASSERT_TRUE(snapshotTaken);
    ASSERT_TRUE(std::filesystem::exists(snapshotFilePath));
    auto size = std::filesystem::file_size(snapshotFilePath);
    ASSERT_GT(size, 0);
}
